# Generated by Django 5.1.6 on 2025-04-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='chemical',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='chemical_waste',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='conveyor_speed',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='developer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='dft',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='grain_filling',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='name_verbose',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='sheen',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='substrate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
