# Generated by Django 5.1.6 on 2025-04-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_table_chemical_table_chemical_waste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='blueprint',
            field=models.ImageField(blank=True, null=True, upload_to='blueprints/'),
        ),
        migrations.AddField(
            model_name='table',
            name='panel',
            field=models.ImageField(blank=True, null=True, upload_to='panels/'),
        ),
    ]
