# Generated by Django 5.1.6 on 2025-04-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_table_collection_table_factory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
